name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: L1SDN_FP_TD8
      id: l1sdn_fp_td8
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 20
        setup-command: ''
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        L1SDN_FP_TD8_RESULTS: "${{steps.l1sdn_fp_td8.outputs.result}}"
      with:
        runners: l1sdn_fp_td8
